server:
  port: 8080

config:
  url: http://facundo-guarnier.com
  puerto: 8080
  personas:
  - nombre: Facundo
    apellido: Guarnier

config-domicilios:
  domicilios:
  - calle: Libertad
    numero: 600
    localidad: Villa Nueva
    provincia: Mendoza

  - calle: San Martin
    numero: 1500
    localidad: Mendoza
    provincia: Mendoza

  - calle: Rio Tunuyán
    numero: 1891
    localidad: Villa Nueva
    provincia: Mendoza